// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAV7AN3AyrIV1MUzy-GYG371SeDCR7JrnA",
      authDomain: "duangiuaky.firebaseapp.com",
      databaseURL: "https://duangiuaky-default-rtdb.firebaseio.com",
      projectId: "duangiuaky",
      storageBucket: "duangiuaky.appspot.com",
      messagingSenderId: "71892798919",
      appId: "1:71892798919:web:47606ef08c91877e0c9de2",
      measurementId: "G-1VTSJX2F4B");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-QtF9dlYXWKIrfS1v1bw-BC90ik0cjx0',
    appId: '1:71892798919:android:f92f17fe2ea3fdfb0c9de2',
    messagingSenderId: '71892798919',
    projectId: 'duangiuaky',
    storageBucket: 'duangiuaky.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA04gqoU-L6r0MbOoRXVqur7Fn51OIjA4Q',
    appId: '1:71892798919:ios:52e4a4934a06896b0c9de2',
    messagingSenderId: '71892798919',
    projectId: 'duangiuaky',
    storageBucket: 'duangiuaky.appspot.com',
    iosBundleId: 'com.example.duangiuaky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA04gqoU-L6r0MbOoRXVqur7Fn51OIjA4Q',
    appId: '1:71892798919:ios:52e4a4934a06896b0c9de2',
    messagingSenderId: '71892798919',
    projectId: 'duangiuaky',
    storageBucket: 'duangiuaky.appspot.com',
    iosBundleId: 'com.example.duangiuaky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV7AN3AyrIV1MUzy-GYG371SeDCR7JrnA',
    appId: '1:71892798919:web:7db3335553b260550c9de2',
    messagingSenderId: '71892798919',
    projectId: 'duangiuaky',
    authDomain: 'duangiuaky.firebaseapp.com',
    storageBucket: 'duangiuaky.appspot.com',
    measurementId: 'G-XNV2B8DTQW',
  );
}
